<a href="https://colab.research.google.com/github/Ethan-Jeong/test_python/blob/master/python_function.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
np.__version__

'1.19.5'

In [ ]:
displacement =  307.0
horsepower = 130.0
weight = 3504.0
accel = 12.0
cylinders = 8
origin = 1

In [ ]:
import numpy as np


In [ ]:
def onehotcylinder(cylinders):
  if cylinders == 3:
    cylinder = np.array([1,0,0,0,0])
  elif cylinders == 4:
    cylinder = np.array([0,1,0,0,0])
  elif cylinders == 5:
    cylinder = np.array([0,0,1,0,0])
  elif cylinders == 6:
    cylinder =  np.array([0,0,0,1,0])
  else: #8 
    cylinder =  np.array([0,0,0,0,1]) 
  return cylinder

In [ ]:
onehotcylinder(4)

array([0, 1, 0, 0, 0])

In [ ]:
x_continus  = np.array([ displacement,horsepower,weight, accel ])
onehotcylinder(cylinders)
org = np.array([1,0,0]) # 1 

In [ ]:
type(x_continus) , type(cylinder) , type(org) , cylinder

(numpy.ndarray, list, numpy.ndarray, [0, 0, 0, 0, 1])

In [ ]:
# np.concatenate((a, b), axis=None)
result = np.round(np.concatenate((x_continus, cylinder , org ), axis=None))


In [ ]:
result.shape , result 

((12,),
 array([3.070e+02, 1.300e+02, 3.504e+03, 1.200e+01, 0.000e+00, 0.000e+00,
        0.000e+00, 0.000e+00, 1.000e+00, 1.000e+00, 0.000e+00, 0.000e+00]))

In [ ]:
# result.reshape(1,12) # result.reshape(-1,result.size)
result = result.reshape(-1,result.size) # 

In [ ]:
result

array([[3.070e+02, 1.300e+02, 3.504e+03, 1.200e+01, 0.000e+00, 0.000e+00,
        0.000e+00, 0.000e+00, 1.000e+00, 1.000e+00, 0.000e+00, 0.000e+00]])

In [ ]:
result.size  , result 

(12, array([[3.070e+02, 1.300e+02, 3.504e+03, 1.200e+01, 0.000e+00, 0.000e+00,
         0.000e+00, 0.000e+00, 1.000e+00, 1.000e+00, 0.000e+00, 0.000e+00]]))

# Function 이해

In [ ]:
first = 21
second = 14
first + second  

35

In [ ]:

def sum(f01,s02):
  first = s02
  second = f01
  result = first + second  
  return result

In [ ]:
sum(31,22)

53

In [ ]:
def sum(f1,f2,f3):
  f = f1
  s = f2
  t = f3
  result = f * s * t
  return result

In [ ]:
sum(21,32,2), sum(31,63,41)

(1344, 80073)

In [ ]:
def diffparam(*var_list, **var_dict): # * List , ** Dictionary
  
  print(var_dict)
  result01 = len(var_list)
  
  return result01

In [ ]:
diffparam(1,2,3, a=2,b=3 )



{'a': 2, 'b': 3}


3